openapi: 3.0.3
info:
  title: Example of api for generate
  description: Example of api for generate
  version: 1.0.0
servers:
  - url: http://localhost:8090/
paths:
  /Tests:
    get:
      summary: List all Tests
      operationId: listTests
      tags:
        - Tests
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of Tests
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tests"
        default:
          description: unexpected TestError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestError"
    post:
      summary: Create a Test
      operationId: createTests
      tags:
        - Tests
      responses:
        '201':
          description: Null response
        default:
          description: unexpected TestError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestError"
  /Tests/{TestId}:
    get:
      summary: Info for a specific Test
      operationId: showTestById
      tags:
        - Tests
      parameters:
        - name: TestId
          in: path
          required: true
          description: The id of the Test to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Test"
        default:
          description: unexpected TestError
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestError"
components:
  schemas:
    Test:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Tests:
      type: array
      items:
        $ref: "#/components/schemas/Test"
    TestError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
